// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sborsh1kmusora/micro-shop/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// InventoryService is an autogenerated mock type for the InventoryService type
type InventoryService struct {
	mock.Mock
}

type InventoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryService) EXPECT() *InventoryService_Expecter {
	return &InventoryService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *InventoryService) Create(ctx context.Context, item *model.Item) (string, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Item) (string, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Item) string); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Item) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type InventoryService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *model.Item
func (_e *InventoryService_Expecter) Create(ctx interface{}, item interface{}) *InventoryService_Create_Call {
	return &InventoryService_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *InventoryService_Create_Call) Run(run func(ctx context.Context, item *model.Item)) *InventoryService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Item))
	})
	return _c
}

func (_c *InventoryService_Create_Call) Return(_a0 string, _a1 error) *InventoryService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_Create_Call) RunAndReturn(run func(context.Context, *model.Item) (string, error)) *InventoryService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uuid
func (_m *InventoryService) Get(ctx context.Context, uuid string) (*model.Item, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Item, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Item); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type InventoryService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *InventoryService_Expecter) Get(ctx interface{}, uuid interface{}) *InventoryService_Get_Call {
	return &InventoryService_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *InventoryService_Get_Call) Run(run func(ctx context.Context, uuid string)) *InventoryService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InventoryService_Get_Call) Return(_a0 *model.Item, _a1 error) *InventoryService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_Get_Call) RunAndReturn(run func(context.Context, string) (*model.Item, error)) *InventoryService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *InventoryService) List(ctx context.Context, filter *model.Filter) ([]*model.Item, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filter) ([]*model.Item, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filter) []*model.Item); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Filter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type InventoryService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *model.Filter
func (_e *InventoryService_Expecter) List(ctx interface{}, filter interface{}) *InventoryService_List_Call {
	return &InventoryService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *InventoryService_List_Call) Run(run func(ctx context.Context, filter *model.Filter)) *InventoryService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Filter))
	})
	return _c
}

func (_c *InventoryService_List_Call) Return(_a0 []*model.Item, _a1 error) *InventoryService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_List_Call) RunAndReturn(run func(context.Context, *model.Filter) ([]*model.Item, error)) *InventoryService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryService creates a new instance of InventoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryService {
	mock := &InventoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
